### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by taichuai** [Jeevesh8/Cross-Lingual-Voice-Cloning#4]
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    args.warm_start, args.n_gpus, args.local_rank, args.group_name, hparams)
  File "train.py", line 211, in train
    for i, batch in enumerate(train_loader):
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zero/anaconda3/envs/tacotron/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zero/TTS/Cross-Lingual-Voice-Cloning/data_utils.py", line 62, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/zero/TTS/Cross-Lingual-Voice-Cloning/data_utils.py", line 35, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/zero/TTS/Cross-Lingual-Voice-Cloning/data_utils.py", line 43, in get_mel
    sampling_rate, self.stft.sampling_rate))
IndexError: tuple index out of range

i got the error: index out of range and i can't find the reason

and the hparams:

        use_saved_learning_rate=False,
        learning_rate=1e-3,
        weight_decay=1e-5,
        grad_clip_thresh=1.0,
        batch_size=10,
        mask_padding=True,  # set model's padded outputs to padded values

        ###############################
        # Speaker and Lang Embeddings #
        ###############################
        speaker_embedding_dim = 64,
        lang_embedding_dim = 3,
        n_langs = 2,
        n_speakers = 9,

        ###############################
        ## Speaker Classifier Params ##
        ###############################
        hidden_sc_dim=256,

        ##############################
        ## Residual Encoder Params  ##
        ##############################
        residual_encoding_dim = 32,          #16 for q(z_l|X) and 16 for q(z_o|X)
        dim_yo = 6,                          #(==n_speakers) dim(y_{o})
        dim_yl = 10,                         #K
        # mcn = 8                              #n for monte carlo sampling of q(z_l|X)and q(z_o|X)
        mcn = 6                              #n for monte carlo sampling of q(z_l|X)and q(z_o|X)

**Comment by taichuai** [comment]
ok, I solved it. It caused by different samplling rate

**Comment by Jeevesh8** [comment]
okay.
